# Default values for gate-teamware.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Host name under which the app will be exposed by the ingress
hostName: "example.gate.ac.uk"
publicUrl: ""

superuser:
  # Email address for the default superuser account.  This account is created
  # by the migration job only in the case where there are no superuser accounts
  # already in the database
  email: teamware-admin@example.com
  # Username for the default superuser
  username: admin
  # Initial password for the default superuser, ignored if existingSecret is set
  password: "admin"
  # Name of an existing secret containing the initial superuser password as the
  # "password" key.
  existingSecret: ""

# Docker registry prefix from which the backend and staticFiles images will be
# pulled - if specified, this value _must_ end with a forward slash, e.g.
imageRegistry: "ghcr.io/gatenlp/"

migrations:
  # Whether to run a job at chart install time to perform the Django migrations -
  # this needs to be set to true on the first install, but could be changed to
  # false for subsequent ones if there are no DB changes.  We deliberately do not
  # run migrations as part of the regular Django startup as this is dangerous
  # when there may be more than one replica of the backend pod.
  run: false
  ttl: 300

  waitFor:
    registry: "ghcr.io/patrickdappollonio/"
    image: "wait-for"
    tag: "latest"
    timeout: "30s"

backend:
  image:
    repository: teamware-backend
    pullPolicy: IfNotPresent
    pullSecrets: []
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  replicaCount: 1
  # Kubernetes secret holding the randomly generated Django secret key.  This MUST exist before
  # installing the chart, and must have an entry named "secret-key" whose value is a random string
  # at least 50 characters in length
  djangoSecret: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  # extra environment variable settings and command arguments to be passed to the django container
  extraEnv: []
  extraArgs: []

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000


staticFiles:
  image:
    repository: teamware-static
    pullPolicy: IfNotPresent
    pullSecrets: []
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  healthPort: 8888

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


ingress:
  # Should we create an ingress to route requests in to Teamware?  If you set this
  # to false then it is your responsibility to set up appropriate routing, so that
  # {publicUrl}/static/* goes to the "static" service and all other requests to
  # {publicUrl} go to the backend service.  Typically this will be done either by
  # deploying another reverse proxy deployment as a LoadBalancer service, or by
  # setting the service type of both the static and backend services to NodePort
  # and using a separate gateway external to the cluster.
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  tls:
    # Should the ingress controller serve over https: (true) or http: (false).
    # If set to false you will also need to override publicUrl above, as the
    # default for that assumes https:
    enabled: true
    # Kubernetes secret holding the TLS certificate for the public hostname.
    # An empty value means that no secretName will be set on the ingress,
    # whether or not this is valid and how it behaves depends on the specific
    # ingress controller in use - for ingress-nginx it will use the default
    # certificate of the controller.
    secret: ""

email:
  # Admin email address, used as the "from" address on automated emails
  adminAddress: ""
  # "smtp" for SMTP(S) sender, "gmail" for GMail API
  backend: ""
  # Should we require activation of new accounts with an emailed token, to
  # verify the email address?
  activationEnabled: false
  smtp:
    # SMTP server name, if backend: "smtp"
    host: ""
    # Port number - typically 25 or 587 for SMTP with no encryption or with
    # STARTTLS, or 465 for "SMTPS" immediate TLS-on-connect.
    port: "587"
    # username, if SMTP server requires authentication
    user: ""
    # kubernetes secret containing the SMTP password as the "password" key
    passwordSecret: ""
    # SMTP security, if required - "TLS" for STARTTLS (typically on port 25 or
    # 587), "SSL" for TLS-on-connect (typically port 465)
    security: ""
    # Name of a TLS secret containing the client key and certificate, if
    # required
    clientCertSecret: ""
  gmail:
    # OAuth client ID for the GMail API
    clientId: ""
    # Name of a Kubernetes secret with keys "client-secret" for the OAuth
    # client secret and "refresh-token" for the GMail API refresh token.
    secretName: ""

# Database settings
postgresql:
  architecture: standalone
  auth:
    database: teamware_db
    username: gate

  # Additional useful settings include persistence.storageClass and persistence.size.
  # If upgrading from an earlier version of this chart, you may also need to set
  # auth.existingSecret: postgres-credentials

# Configure regular database backups to S3 (or compatible) storage
backup:
  image: "schickling/postgres-backup-s3:latest"
  pullPolicy: Always
  # API endpoint, if not the public Amazon S3
  endpoint: ""
  # S3 region e.g. us-east-1
  region: ""
  # Bucket to which the backups should be stored
  bucketName: ""
  # common key prefix for all the backups - the schedule name will be added
  # after this prefix to construct the full target location
  keyPrefix: ""
  # Kubernetes secret with keys "access-key-id" and "secret-key" that have
  # write access to the specified bucket
  credentialsSecret: ""

  concurrencyPolicy: ""
  failedJobsHistoryLimit: ""
  successfulJobsHistoryLimit: ""

  # Backup schedule.  Keys in the map are the name of the backup schedule
  # (e.g. daily, weekly), values are the cron expression defining the schedule.
  # The actual backup files will be placed at
  # s3://<bucketName>/<keyPrefix>/<schedule-name>/<database-name>_<timestamp>.sql.gz
  #
  # Note that the cron job creates new backups but does not expire old ones -
  # if you want old backups to expire (or be moved to cheaper storage like
  # infrequent access or Glacier) then you should configure that at the bucket
  # level using S3 lifecycle rules.
  schedule: {}
  # daily:   "13 01 * * *"
  # weekly:  "13 02 * * 0"
  # monthly: "13 00 1 * *"
