#!/bin/sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE USER $DJANGO_DB_USER WITH PASSWORD '$DJANGO_DB_PASSWORD';
CREATE DATABASE $DJANGO_DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $DJANGO_DB_NAME TO $DJANGO_DB_USER;
CREATE USER $DB_BACKUP_USER WITH PASSWORD '$DB_BACKUP_PASSWORD';
GRANT CONNECT ON DATABASE $DJANGO_DB_NAME TO $DB_BACKUP_USER;
GRANT USAGE ON SCHEMA public TO $DB_BACKUP_USER;
EOSQL
