version: "3.9"

services:

  backend:
    image: annotate-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
      - DJANGO_DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
    depends_on:
      - db
    networks:
      - annotations-docker

  nginx:
    image: annotate-static:latest
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
      - db
    networks:
      - annotations-docker


  db:
    image: postgres:12-alpine
    restart: always
    env_file: 
      - ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_SUPERUSER_PASSWORD}
      - DJANGO_DB_NAME
      - DJANGO_DB_USER=${DB_USERNAME}
      - DJANGO_DB_PASSWORD=${DB_PASSWORD}
      - DB_BACKUP_USER
      - DB_BACKUP_PASSWORD
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./create-django-db.sh:/docker-entrypoint-initdb.d/001-create-django-db.sh
    networks:
      - annotations-docker

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - /var/opt/annotations-pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DJANGO_DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

volumes:
  postgresql-data:

networks:
  annotations-docker:
    driver: bridge