version: "3.8"

services:

  backend:
    build: .
    command: ./run-server.sh
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
      - DJANGO_DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
    # ports:
    #   - "127.0.0.1:8000:8000"
    secrets:
      - django-secrets
    # depends_on:
    #   - db
    volumes:
      - django-static:/app/static
      - logs/:/logs/
    networks:
      - django-nginx

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - django-static:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - backend
      # - db
    networks:
      - django-nginx


#   db:
#     image: postgres:12-alpine
#     restart: always
#     expose:
#       - "5432"
#     env_file: 
#       - ./.env
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=${PG_SUPERUSER_PASSWORD}
#       - DJANGO_DB_NAME
#       - DJANGO_DB_USER=${DB_USERNAME}
#       - DJANGO_DB_PASSWORD=${DB_PASSWORD}
#       - DB_BACKUP_USER
#       - DB_BACKUP_PASSWORD
#     volumes:
#       - postgresql-data:/var/lib/postgresql/data
#       - ./create-django-db.sh:/docker-entrypoint-initdb.d/001-create-django-db.sh

volumes:
  django-static:
  logs:
#   postgresql-data:

secrets:
  django-secrets:
    file: secret.py

networks:
  django-nginx:
    driver: bridge