# Generated by Django 3.2 on 2021-07-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='activate_account_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='activate_account_token_expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='reset_password_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='reset_password_token_expire',
            field=models.DateTimeField(null=True),
        ),
    ]
