# Generated by Django 3.2 on 2021-07-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='manages',
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
