# Generated by Django 3.2 on 2021-07-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210709_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceuser',
            old_name='manager',
            new_name='is_manager',
        ),
    ]
