# Generated by Django 3.2 on 2021-07-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210726_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceuser',
            old_name='is_activated',
            new_name='is_account_activated',
        ),
    ]
