# Generated by Django 3.2 on 2021-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_is_activated_serviceuser_is_account_activated'),
        ('backend', '0003_rename_manager_serviceuser_is_manager'),
    ]

    operations = [
    ]
