# Generated by Django 3.2 on 2021-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210430_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
