# Generated by Django 3.2 on 2021-07-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_merge_20210727_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='receive_mail_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
