# Generated by Django 3.2 on 2021-10-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_serviceuser_receive_mail_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='activate_account_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='activate_account_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='annotates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotators', to='backend.project'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='reset_password_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='reset_password_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
