# Generated by Django 3.2 on 2021-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210528_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data',
        ),
        migrations.AddField(
            model_name='project',
            name='annotations_per_doc',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='project',
            name='annotator_max_annotation',
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name='project',
            name='configuration',
            field=models.JSONField(default=[]),
        ),
    ]
