# Generated by Django 3.2 on 2021-10-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211026_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document_input_preview',
            field=models.JSONField(default=dict),
        ),
    ]
