# Generated by Django 3.2 on 2021-06-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='configuration',
            field=models.JSONField(default=list),
        ),
    ]
