# Generated by Django 3.2 on 2021-10-26 01:21

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_project_document_input_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document_input_preview',
            field=models.JSONField(default=backend.models.default_document_input_preview),
        ),
    ]
