# Generated by Django 3.2 on 2021-06-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_project_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='annotation',
            name='completed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='rejected',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
