# Generated by Django 3.2 on 2021-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_project_document_input_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id_field',
            field=models.TextField(default='name'),
        ),
    ]
