# Generated by Django 3.2 on 2021-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210608_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='timeout_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
