# Generated by Django 3.2 on 2021-11-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_project_id_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id_field',
            new_name='document_id_field',
        ),
    ]
