# Generated by Django 3.2.8 on 2021-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_id_field_project_document_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_document_reject',
            field=models.BooleanField(default=True),
        ),
    ]
