# Generated by Django 3.2 on 2021-06-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_annotation_timeout_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='timeout_minutes',
        ),
        migrations.AddField(
            model_name='annotation',
            name='times_out_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
