# Generated by Django 3.2.8 on 2022-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_project_allow_document_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='time_to_complete',
            field=models.FloatField(default=None, null=True),
        ),
    ]
