# Generated by Django 3.2.8 on 2022-03-18 16:20
from django.utils import timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_annotation_time_to_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceuser',
            old_name='annotates',
            new_name='annotates_old',
        ),
    ]
