# Generated by Django 3.2.8 on 2022-03-18 16:20
from django.utils import timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20220318_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='annotates_old',
        ),
    ]
