# Generated by Django 3.2.8 on 2022-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015a_remove_annotates_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatorproject',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
