# Generated by Django 3.2.8 on 2022-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_annotatorproject_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.IntegerField(choices=[(0, 'Annotation'), (1, 'Training'), (2, 'Test')], default=0),
        ),
    ]
