# Generated by Django 3.2 on 2022-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_project_document_gold_standard_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatorproject',
            name='allowed_to_annotate',
            field=models.BooleanField(default=False),
        ),
    ]
