# Generated by Django 3.2 on 2022-03-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_annotatorproject_allowed_to_annotate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatorproject',
            name='test_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='annotatorproject',
            name='training_score',
            field=models.FloatField(default=0),
        ),
    ]
