# Generated by Django 3.2 on 2022-05-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020a_training_score_not_null'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='can_annotate_after_passing_test',
            new_name='can_annotate_after_passing_training_and_test',
        ),
    ]
