# Generated by Django 3.2 on 2022-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_rename_can_annotate_after_passing_test_project_can_annotate_after_passing_training_and_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_annotation_change',
            field=models.BooleanField(default=True),
        ),
    ]
