# Generated by Django 3.2 on 2022-07-01 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_project_allow_annotation_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='backend.annotation')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_annotations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
