# Generated by Django 3.2.15 on 2022-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_rename_data_annotation__data'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='doc_format_pref',
            field=models.IntegerField(choices=[(0, 'JSON'), (1, 'CSV')], default=0),
        ),
    ]
