# Generated by Django 3.2.15 on 2022-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_serviceuser_doc_format_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document_input_preview_csv',
            field=models.TextField(default=''),
        ),
    ]
