# Generated by Django 3.2.15 on 2022-11-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_project_document_pre_annotation_field'),
        ('backend', '0026_project_document_input_preview_csv'),
    ]

    operations = [
    ]
