# Generated by Django 3.2.15 on 2022-11-16 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_project_document_input_preview_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
