# Generated by Django 3.2.15 on 2023-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_project_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='agreed_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
