# Generated by Django 3.2.15 on 2023-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_serviceuser_agreed_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
