{{- range $name, $cron := .Values.backup.schedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "backup-%s-%s" $name (include "gate-teamware.fullname" $) | trunc 52 | trimSuffix "-" }}
  labels:
    {{- include "gate-teamware.labels" $ | nindent 4 }}
    {{- include "gate-teamware.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: backup-{{ $name }}
spec:
  schedule: {{ $cron | quote }}
  {{- if $.Values.backup.concurrencyPolicy }}
  concurrencyPolicy: {{ $.Values.backup.concurrencyPolicy }}
  {{- end }}
  {{- if ne $.Values.backup.failedJobsHistoryLimit "" }}
  failedJobsHistoryLimit: {{ $.Values.backup.failedJobsHistoryLimit }}
  {{- end }}
  {{- if ne $.Values.backup.successfulJobsHistoryLimit "" }}
  successfulJobsHistoryLimit: {{ $.Values.backup.successfulJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "gate-teamware.labels" $ | nindent 12 }}
            {{- include "gate-teamware.selectorLabels" $ | nindent 12 }}
            app.kubernetes.io/component: backup-{{ $name }}
        spec:
          serviceAccountName: {{ include "gate-teamware.serviceAccountName" $ }}
          restartPolicy: Never
          containers:
            - name: backup
              image: {{ $.Values.backup.image | quote }}
              imagePullPolicy: {{ $.Values.backup.pullPolicy }}
              env:
              - name: S3_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ $.Values.backup.credentialsSecret | required "backup.credentialsSecret is required" | quote }}
                    key: access-key-id
              - name: S3_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ $.Values.backup.credentialsSecret | required "backup.credentialsSecret is required" | quote }}
                    key: secret-key
              - name: S3_BUCKET
                value: {{ $.Values.backup.bucketName | required "backup.bucketName is required" | quote }}
              - name: S3_PREFIX
                value: {{ with $.Values.backup.keyPrefix }}{{ . }}/{{ end }}{{ $name }}
              {{- if $.Values.backup.endpoint }}
              - name: S3_ENDPOINT
                value: {{ $.Values.backup.endpoint | quote }}
              {{- end }}
              {{- if $.Values.backup.region }}
              - name: S3_REGION
                value: {{ $.Values.backup.region | quote }}
              {{- end }}
              - name: POSTGRES_HOST
                value: {{ include "postgresql.primary.fullname" $.Subcharts.postgresql | quote }}
              - name: POSTGRES_PORT
                value: {{ include "postgresql.service.port" $.Subcharts.postgresql | quote }}
              - name: POSTGRES_DATABASE
                value: {{ $.Values.postgresql.auth.database | quote }}
              - name: POSTGRES_USER
                value: {{ $.Values.postgresql.auth.username | quote }}
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ include "postgresql.secretName" $.Subcharts.postgresql }}
                    key: password

---
{{- end }}{{/* range over schedule */}}
