{{- if .Values.ingress.enabled }}
{{- $fullName := include "gate-teamware.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gate-teamware.labels" . | nindent 4 }}
    {{- include "gate-teamware.selectorLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostName | quote }}
      {{- with .Values.ingress.tls.secret }}
      secretName: {{ . | quote }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.hostName | quote }}
      http:
        paths:
          - pathType: "Prefix"
            path: "/static"
            backend:
              service:
                name: {{ $fullName }}-static
                port:
                  number: {{ .Values.staticFiles.service.port }}
          - pathType: "Prefix"
            path: "/"
            backend:
              service:
                name: {{ $fullName }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}