{{- if not .Values.superuser.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gate-teamware.superuserSecret" . | quote }}
  labels:
    {{- include "gate-teamware.labels" $ | nindent 4 }}
    {{- include "gate-teamware.selectorLabels" $ | nindent 4 }}
data:
  password: {{ .Values.superuser.password | b64enc | quote }}
{{- end }}
