name: CI
on:
  push:
    branches: [ frontend-testing ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "annotation-tool"
          environment-file: environment.yml
#      - name: Use Node.js v14
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - name: Install npm packages
#        run: npm install
      - run: conda activate annotation-tool
      - run: conda info
      - run: conda list
      - run: conda config --show
#      - name: Run backend test
#        run: npm run test:backend
#      - name: Run frontend test
#        run: npm run test:frontend
#      - name: Run integration test
#        run: npm run test:integration

