name: Test image build and run Integration tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate env
        shell: bash
        run: |
          export MAIN_IMAGE=teamware-main
          export STATIC_IMAGE=teamware-static
          
          ./generate-docker-env.sh

          # Remove container registry address
          sed -i 's/ghcr.io\/gatenlp\///g' .env

          # Display the environment variable file for the logs
          cat .env

      - name: Set up Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: integration-test-docker-cache-{hash}
          restore-keys: |
            integration-test-docker-cache-
      
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          ./build-images.sh
          
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run integration tests with cypress
        uses: cypress-io/github-action@v2
        with:
          start: /bin/bash deploy.sh integration
          wait-on: 'http://localhost:8076'
          config: baseUrl=http://localhost:8076
          env: TESTENV=container
