name: Run backend and frontend tests inside docker image
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate env
        shell: bash
        run: |
          export MAIN_IMAGE=teamware-test
          export IMAGE_REGISTRY=''
          ./generate-docker-env.sh
      

      - name: Run the backend and frontend tests in containers
        run: docker build -t teamware-test:latest --target test .

          docker-compose up -d
          
          docker run --rm --entrypoint npm teamware-test:latest run test:pytest

          docker run --rm --entrypoint npm teamware-test:latest run test:frontend
