name: Run backend and frontend tests inside docker image
on:
  push:
    branches:
      - docker-tests
  #     - main
  #     - dev
  # pull_request:
  #   branches:
  #     - main
  #     - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate env
        shell: bash
        run: |
          ./generate-env.sh
      
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          docker build -t annotate-test:latest --target test .
          
          # Run backend tests
          docker run --rm --entrypoint npm annotate-test:latest run test:backend

          # Run frontend tests
          docker run --rm --entrypoint npm annotate-test:latest run test:frontend
