name: Run backend and frontend tests inside docker image
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run the backend and frontend tests in containers
        run: |
          export MAIN_IMAGE=teamware-main
          export STATIC_IMAGE=teamware-static
          
          ./generate-docker-env.sh

          # Remove container registry address
          sed -i 's/ghcr.io\/gatenlp\///g' .env

          cat .env

          docker build -t teamware-main:latest --target test .

          docker-compose up -d backend
          docker-compose up -d db
          
          docker-compose exec web npm run test:pytest

          docker-compose exec web npm run test:frontend
